import uuid
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, EmailStr

class SubscriberBase(BaseModel):
    email: EmailStr = Field(..., max_length=100)

class SubscriberCreate(SubscriberBase):
    pass

class SubscriberUpdate(BaseModel):
    is_active: Optional[bool] = None

class SubscriberOut(SubscriberBase):
    id: uuid.UUID
    is_active: bool
    registration_date: datetime

    model_config = {"from_attributes": True}

#FOR EMAIL DRAFT
class EmailDraft(BaseModel):
    subject: str = Field(..., max_length=150)
    html_content: str = Field(...) # Catch raw HTML generated by the admin