"""Add: is_active Field to Subscriber model.

Revision ID: 0f0ee4ec8492
Revises: 1ba02ba38a88
Create Date: 2026-03-27 14:25:29.762743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0ee4ec8492'
down_revision: Union[str, Sequence[str], None] = '1ba02ba38a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('subscribers', 'origin_inquiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('origin_inquiry', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('subscribers', 'is_active')
    # ### end Alembic commands ###
