"""updates: changing datatype to SocialNetwork db model. Now url is an HttpUrl pydantic type.

Revision ID: 16d008fe212a
Revises: 0f0ee4ec8492
Create Date: 2026-03-30 17:43:49.920886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d008fe212a'
down_revision: Union[str, Sequence[str], None] = '0f0ee4ec8492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
