"""Add: is_active Field to SocialNetwork model.

Revision ID: 1ba02ba38a88
Revises: 7160d1c6df3e
Create Date: 2026-03-27 10:17:57.473384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba02ba38a88'
down_revision: Union[str, Sequence[str], None] = '7160d1c6df3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_networks', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_networks', 'is_active')
    # ### end Alembic commands ###
