"""Adding open-close time Settings db model

Revision ID: 5df9c3aca1ba
Revises: 16d008fe212a
Create Date: 2026-04-01 15:28:21.016294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df9c3aca1ba'
down_revision: Union[str, Sequence[str], None] = '16d008fe212a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('open_time', sa.String(length=5), nullable=True))
    op.add_column('site_settings', sa.Column('close_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'close_time')
    op.drop_column('site_settings', 'open_time')
    # ### end Alembic commands ###
