"""add_seo_fields

Revision ID: 819e23771ca9
Revises: b1ad095eae91
Create Date: 2026-03-26 14:42:52.810746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819e23771ca9'
down_revision: Union[str, Sequence[str], None] = 'b1ad095eae91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('meta_title', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('categories', sa.Column('meta_keywords', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'meta_keywords')
    op.drop_column('categories', 'meta_description')
    op.drop_column('categories', 'meta_title')
    # ### end Alembic commands ###
