"""update: url field changed from httpurl to str

Revision ID: 99c90cfe8785
Revises: 5df9c3aca1ba
Create Date: 2026-04-01 17:38:16.971560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c90cfe8785'
down_revision: Union[str, Sequence[str], None] = '5df9c3aca1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
