"""add_seo_fields

Revision ID: b1ad095eae91
Revises: 67db3053fec4
Create Date: 2026-03-26 14:42:05.463723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ad095eae91'
down_revision: Union[str, Sequence[str], None] = '67db3053fec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('products', sa.Column('meta_title', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('products', sa.Column('meta_keywords', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'meta_keywords')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
