"""Updated: SiteSettings Model alembic revision autogenerat, adding metatags fields

Revision ID: dd34c1f7cfdc
Revises: 32297fa95b80
Create Date: 2026-03-26 16:36:26.290244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd34c1f7cfdc'
down_revision: Union[str, Sequence[str], None] = '32297fa95b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('meta_title', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('site_settings', sa.Column('meta_keywords', sa.String(length=255), nullable=True))
    op.drop_column('site_settings', 'seo_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('seo_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('site_settings', 'meta_keywords')
    op.drop_column('site_settings', 'meta_description')
    op.drop_column('site_settings', 'meta_title')
    # ### end Alembic commands ###
