"""Add: Field is_active in SiteSettings model.

Revision ID: eec0f985a050
Revises: dd34c1f7cfdc
Create Date: 2026-03-27 09:16:32.382613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec0f985a050'
down_revision: Union[str, Sequence[str], None] = 'dd34c1f7cfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'is_active')
    # ### end Alembic commands ###
